# Generated by Django 5.2.5 on 2026-01-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2')])),
                ('time', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=255)),
                ('speakers', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
    ]
