# Generated by Django 5.2.5 on 2026-01-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
