# Generated by Django 5.2.5 on 2026-01-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0002_agendaitem_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('day1', 'Day 1'), ('day2', 'Day 2')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('activity', models.CharField(max_length=200)),
                ('speakers', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.DeleteModel(
            name='AgendaItem',
        ),
    ]
