# Generated by Django 6.0.2 on 2026-02-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fts', '0004_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
